language: julia
os:
  - linux
julia:
  - 1.0
  - 1.1
  - nightly

# addons:
#   apt:
#     packages:
#       - python3-matplotlib

notifications:
  email: false

matrix:
  allow_failures:
    - julia: nightly

# code coverage
after_success:
  # push coverage results to Codecov
  - julia -e 'using Pkg; cd(Pkg.dir("StableDQMC")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  # push coverage results to Coveralls
  - julia -e 'using Pkg; cd(Pkg.dir("StableDQMC")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'

# # generate docs
# jobs:
#   include:
#     - stage: "Documentation"
#       julia: 1.0
#       os: linux
#       script:
#         - julia --project=docs/ --color=yes -e 'using Pkg; Pkg.instantiate();
#                                     Pkg.add(PackageSpec(path=pwd()))'
#         - julia --project=docs/ --color=yes docs/make.jl
#       after_success: skip
